Plex: 
  url: https://url:32400
  token: 
MasterList: 
  UseMaster: No
  MasterRandom: No
  # If the path for the Master List is left blank the script will create the path 
  # based on if Monthly, Weekly, or Daily are set to be used in the Master List 
  # otherwise you can populate the path with your own set of trailers
  Path: 
Monthly: 
  Jan: /path/to/file.mp4
  Feb: 
  Mar: 
  Apr: 
  May: 
  June: 
  July: 
  Aug: 
  Sept: 
  Oct: 
  Nov: 
  Dec: 
  MasterList: No
  MasterListValue: 
  UseMonthly: Yes
Weekly:
  StartDate: 
  EndDate: 
  Path: 
  MasterList: No
  UseWeekly: No
Daily:
  StartDate: 
  EndDate: 
  Path: 
  MasterList: No
  UseDaily: No
Misc:
  Path: 
  StaticTrailer: /trailer/to/play/at/end.mp4
  #Enter the number of trailers to use ex: Path contains 5 trailers you set this value to 2 the program will pick two at random as well as the static trailer to play in order:
  TrailerListLength: 
  UseMisc: No
